### ISSUE TITLE
Update about.md

### ISSUE THREAD

**Issue by yihui** [apreshill/blogdown-demo#1]
@apreshill Could you update the About page to reflect what this site is really about? Thanks!

**Comment by apreshill** [comment]
Updated- let me know if you had something different in mind!

**Comment by yihui** [comment]
It will be great if you can be a little more specific, e.g. a brief summary of the posts.

**Comment by apreshill** [comment]
Oh! I wrote up more of a summary of each post too- about to push...sorry I thought baby was waking up so I pushed what I had- then she went back to sleep so I thought I would do more! Let me know if it is overkill then...

**Comment by yihui** [comment]
💯 Thanks!
