### ISSUE TITLE
default argument in blogdown::new_post has changed

### ISSUE THREAD

**Issue by cderv** [apreshill/blogdown-demo#18]
From rstudio/blogdown#379, we discovered that there was a change in blogdown::new_post() argument name that was of impact to new users and still documented. It is about rmd = FALSE that no more exist and was replace by ext = getOption('blogdown.ext', '.md') instead.

This is here
* https://blogdown-demo.rbind.io/2017/10/06/adding-r-code-to-r-markdown-posts/
* https://github.com/rbind/blogdown-demo/blob/master/content/post/2017-10-06-adding-r-code-to-r-markdown-posts.Rmd

Should we just update the line in question in an old post or should there be a new post replacing the old one ? I wonder because posts have dates... 🤔

**Comment by yihui** [comment]
I think it is fine to just update the old post. Thanks for the report!

**Comment by yihui** [comment]
@apreshill Could you do it when you have a minute? Thank you!

**Comment by apreshill** [comment]
Thanks for the catch!
