### ISSUE TITLE
The citation post

### ISSUE THREAD

**Issue by yihui** [apreshill/blogdown-demo#2]
I just tweaked the post a little bit. In general, I hope to keep these examples minimal. While I think Example 1 is an excellent example, I'm concerned about what a beginner thinks when she read the Rmd source. The problem is that, in order to learn how to use citations in blogdown, she would probably need to understand how dplyr/ggplot2/ggthemes work, which is a totally orthogonal task.

Instead of trying to fully reproduce a figure in actual publications, I suggest you teach users how to find the BibTeX entries, which can be more generally useful. For example, you can obtain a BibTeX entry from Google Scholar:

![image](https://user-images.githubusercontent.com/163582/31235867-2bd548c0-a9b8-11e7-9139-dbe6da0b4e38.png)

What do you think?

**Comment by yihui** [comment]
One more thing about the post: if you don't mind, let's stick to the [typesetting convention](https://bookdown.org/yihui/blogdown/software-info.html): `**bold**` for package names, and `` `code` `` for function names.

**Comment by yihui** [comment]
Actually it is probably also worth mentioning that the .bib files can be saved elsewhere, in which case the user needs to specify the relative path. For example, if foo.bib is saved under `static/bib/foo.bib`, the `bibliography` filed in a post `content/post/hello-world.Rmd` should be `../../static/bib/foo.bib`.

**Comment by apreshill** [comment]
Got it- I will simplify tomorrow. Thanks!
